import { SmartPatchKnob, SmartPatchKnobId } from "./types";

export const SMART_PATCH_KNOBS: Record<SmartPatchKnobId, SmartPatchKnob> = {
  "drums.gain": {
    id: "drums.gain",
    label: "Drum Gain",
    description: "Adjusts drum instrument gain.",
    min: 0,
    max: 1.2,
    defaultDelta: 0.12,
  },
  "drums.decay": {
    id: "drums.decay",
    label: "Drum Decay",
    description: "Adjusts drum instrument decay time.",
    min: 0,
    max: 0.6,
    defaultDelta: 0.03,
  },
  "synth.cutoff": {
    id: "synth.cutoff",
    label: "Synth Cutoff",
    description: "Adjusts synth filter cutoff frequency.",
    min: 60,
    max: 12000,
    defaultDelta: -1200,
  },
  "synth.lofiAmount": {
    id: "synth.lofiAmount",
    label: "Lo-fi Amount",
    description: "Adjusts synth lo-fi texture amount.",
    min: 0,
    max: 1,
    defaultDelta: 0.2,
  },
  "song.swing": {
    id: "song.swing",
    label: "Song Swing",
    description: "Adjusts global swing amount.",
    min: 0,
    max: 0.45,
    defaultDelta: 0.08,
  },
  "track.gain": {
    id: "track.gain",
    label: "Track Gain",
    description: "Adjusts selected track gain.",
    min: 0,
    max: 1.2,
    defaultDelta: 0.08,
  },
  "variation.pitchShiftA": {
    id: "variation.pitchShiftA",
    label: "Variation Shift A",
    description: "Pitch shift for first variation accent.",
    min: -12,
    max: 12,
    defaultDelta: 2,
  },
  "variation.pitchShiftB": {
    id: "variation.pitchShiftB",
    label: "Variation Shift B",
    description: "Pitch shift for second variation accent.",
    min: -12,
    max: 12,
    defaultDelta: -3,
  },
  "synth.subOscMix": {
    id: "synth.subOscMix",
    label: "Sub Osc Mix",
    description: "Blend in a sub oscillator one octave down.",
    min: 0,
    max: 1,
    defaultDelta: 0.08,
  },
  "synth.noiseMix": {
    id: "synth.noiseMix",
    label: "Noise Mix",
    description: "Blend in filtered noise for texture.",
    min: 0,
    max: 1,
    defaultDelta: 0.06,
  },
  "synth.stereoWidth": {
    id: "synth.stereoWidth",
    label: "Stereo Width",
    description: "Spread oscillator layers across stereo field.",
    min: 0,
    max: 1,
    defaultDelta: 0.1,
  },
  "synth.filterEnvAmount": {
    id: "synth.filterEnvAmount",
    label: "Filter Env Amount",
    description: "Controls filter envelope sweep depth.",
    min: 0,
    max: 1,
    defaultDelta: 0.12,
  },
};

export const listSmartPatchKnobs = (): SmartPatchKnob[] => Object.values(SMART_PATCH_KNOBS);
