import { InstrumentParams, TrackType } from "../types/song";

export interface InstrumentPreset {
  id: string;
  label: string;
  type: TrackType;
  params: InstrumentParams;
}

type NumericInstrumentField = Exclude<keyof InstrumentParams, "oscWaveformA" | "oscWaveformB">;

const numericInstrumentFields: NumericInstrumentField[] = [
  "attack",
  "decay",
  "sustain",
  "release",
  "cutoff",
  "resonance",
  "gain",
  "lofiAmount",
  "detune",
  "drive",
  "vibratoRate",
  "vibratoDepth",
  "oscMix",
  "subOscMix",
  "noiseMix",
  "stereoWidth",
  "filterEnvAmount",
];

const nearlyEqual = (a: number, b: number) => Math.abs(a - b) < 0.000001;

export const INSTRUMENT_PRESETS: InstrumentPreset[] = [
  {
    id: "synth-bright-lead",
    label: "Bright Lead",
    type: "synth",
    params: {
      attack: 0.01,
      decay: 0.16,
      sustain: 0.46,
      release: 0.2,
      cutoff: 3200,
      resonance: 1.3,
      gain: 0.5,
      lofiAmount: 0,
      detune: 8,
      drive: 0.16,
      vibratoRate: 5.8,
      vibratoDepth: 10,
      oscWaveformA: "sawtooth",
      oscWaveformB: "square",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-warm-pad",
    label: "Warm Pad",
    type: "synth",
    params: {
      attack: 0.08,
      decay: 0.36,
      sustain: 0.68,
      release: 0.5,
      cutoff: 1800,
      resonance: 0.8,
      gain: 0.42,
      lofiAmount: 0.1,
      detune: 12,
      drive: 0.1,
      vibratoRate: 3.8,
      vibratoDepth: 6,
      oscWaveformA: "triangle",
      oscWaveformB: "sine",
      oscMix: 0.55,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-lofi-key",
    label: "Lo-fi Keys",
    type: "synth",
    params: {
      attack: 0.015,
      decay: 0.22,
      sustain: 0.42,
      release: 0.3,
      cutoff: 980,
      resonance: 1.8,
      gain: 0.44,
      lofiAmount: 0.45,
      detune: 5,
      drive: 0.34,
      vibratoRate: 4.6,
      vibratoDepth: 5,
      oscWaveformA: "square",
      oscWaveformB: "triangle",
      oscMix: 0.48,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-analog-bass",
    label: "Analog Bass",
    type: "synth",
    params: {
      attack: 0.005,
      decay: 0.2,
      sustain: 0.35,
      release: 0.16,
      cutoff: 1200,
      resonance: 1.6,
      gain: 0.62,
      lofiAmount: 0.03,
      detune: 4,
      drive: 0.28,
      vibratoRate: 1.8,
      vibratoDepth: 2.5,
      oscWaveformA: "square",
      oscWaveformB: "sawtooth",
      oscMix: 0.3,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-sub-bass",
    label: "Sub Bass",
    type: "synth",
    params: {
      attack: 0.008,
      decay: 0.14,
      sustain: 0.42,
      release: 0.2,
      cutoff: 800,
      resonance: 0.7,
      gain: 0.7,
      lofiAmount: 0,
      detune: 1.5,
      drive: 0.18,
      vibratoRate: 0.8,
      vibratoDepth: 1.2,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.2,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-supersaw",
    label: "Supersaw",
    type: "synth",
    params: {
      attack: 0.02,
      decay: 0.3,
      sustain: 0.58,
      release: 0.38,
      cutoff: 3600,
      resonance: 0.9,
      gain: 0.5,
      lofiAmount: 0,
      detune: 18,
      drive: 0.22,
      vibratoRate: 4.2,
      vibratoDepth: 7,
      oscWaveformA: "sawtooth",
      oscWaveformB: "sawtooth",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-pluck",
    label: "Pluck",
    type: "synth",
    params: {
      attack: 0,
      decay: 0.1,
      sustain: 0.08,
      release: 0.09,
      cutoff: 4200,
      resonance: 2.4,
      gain: 0.52,
      lofiAmount: 0.04,
      detune: 7,
      drive: 0.15,
      vibratoRate: 5.2,
      vibratoDepth: 3,
      oscWaveformA: "triangle",
      oscWaveformB: "square",
      oscMix: 0.55,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-bell",
    label: "Bell",
    type: "synth",
    params: {
      attack: 0.002,
      decay: 0.5,
      sustain: 0.12,
      release: 0.5,
      cutoff: 6500,
      resonance: 2.2,
      gain: 0.38,
      lofiAmount: 0,
      detune: 10,
      drive: 0.06,
      vibratoRate: 6.5,
      vibratoDepth: 9,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.65,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-acid-lead",
    label: "Acid Lead",
    type: "synth",
    params: {
      attack: 0.001,
      decay: 0.18,
      sustain: 0.34,
      release: 0.13,
      cutoff: 1700,
      resonance: 4.4,
      gain: 0.5,
      lofiAmount: 0.02,
      detune: 6,
      drive: 0.36,
      vibratoRate: 3.2,
      vibratoDepth: 4.5,
      oscWaveformA: "sawtooth",
      oscWaveformB: "square",
      oscMix: 0.45,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-tight-kit",
    label: "Tight Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.09,
      sustain: 0,
      release: 0.04,
      cutoff: 8600,
      resonance: 0.2,
      gain: 0.72,
      lofiAmount: 0,
      detune: 0,
      drive: 0.06,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-heavy-kit",
    label: "Heavy Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.18,
      sustain: 0,
      release: 0.08,
      cutoff: 7000,
      resonance: 0.4,
      gain: 0.92,
      lofiAmount: 0.08,
      detune: 0,
      drive: 0.18,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-dusty-kit",
    label: "Dusty Kit",
    type: "drums",
    params: {
      attack: 0.002,
      decay: 0.14,
      sustain: 0,
      release: 0.07,
      cutoff: 5200,
      resonance: 0.5,
      gain: 0.7,
      lofiAmount: 0.35,
      detune: 0,
      drive: 0.22,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-house-kit",
    label: "House Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.13,
      sustain: 0,
      release: 0.05,
      cutoff: 9000,
      resonance: 0.15,
      gain: 0.78,
      lofiAmount: 0.02,
      detune: 0,
      drive: 0.12,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-boom-bap",
    label: "Boom Bap",
    type: "drums",
    params: {
      attack: 0.002,
      decay: 0.2,
      sustain: 0,
      release: 0.09,
      cutoff: 4300,
      resonance: 0.75,
      gain: 0.82,
      lofiAmount: 0.42,
      detune: 0,
      drive: 0.34,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-airy-kit",
    label: "Airy Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.1,
      sustain: 0,
      release: 0.04,
      cutoff: 9800,
      resonance: 0.2,
      gain: 0.66,
      lofiAmount: 0,
      detune: 0,
      drive: 0.06,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
];

export const getPresetsForType = (type: TrackType): InstrumentPreset[] =>
  INSTRUMENT_PRESETS.filter((preset) => preset.type === type);

export const getMatchingPresetId = (type: TrackType, params: InstrumentParams): string | null => {
  const match = getPresetsForType(type).find((preset) =>
    preset.params.oscWaveformA === params.oscWaveformA &&
    preset.params.oscWaveformB === params.oscWaveformB &&
    numericInstrumentFields.every((field) => nearlyEqual(preset.params[field], params[field]))
  );
  return match?.id ?? null;
};


