import { InstrumentParams, Track } from "../types/song";

export interface InstrumentPreset {
  id: string;
  label: string;
  type: Track["type"];
  params: InstrumentParams;
  send?: Partial<Track["send"]>;
}

type NumericInstrumentField = Exclude<keyof InstrumentParams, "oscWaveformA" | "oscWaveformB">;

const numericInstrumentFields: NumericInstrumentField[] = [
  "attack",
  "decay",
  "sustain",
  "release",
  "cutoff",
  "resonance",
  "gain",
  "lofiAmount",
  "detune",
  "drive",
  "vibratoRate",
  "vibratoDepth",
  "oscMix",
  "subOscMix",
  "noiseMix",
  "stereoWidth",
  "filterEnvAmount",
];

const nearlyEqual = (a: number, b: number) => Math.abs(a - b) < 0.000001;
export const DEFAULT_PRESET_SEND: Track["send"] = {
  delay: 0,
  reverb: 0,
  delayTone: 0.72,
  reverbTone: 0.62,
  reverbLowCut: 0.24,
  delayBus: "custom",
  reverbBus: "custom",
};

export const INSTRUMENT_PRESETS: InstrumentPreset[] = [
  {
    id: "synth-bright-lead",
    label: "Bright Lead",
    type: "synth",
    params: {
      attack: 0.01,
      decay: 0.16,
      sustain: 0.46,
      release: 0.2,
      cutoff: 3200,
      resonance: 1.3,
      gain: 0.5,
      lofiAmount: 0,
      detune: 8,
      drive: 0.16,
      vibratoRate: 5.8,
      vibratoDepth: 10,
      oscWaveformA: "sawtooth",
      oscWaveformB: "square",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-warm-pad",
    label: "Warm Pad",
    type: "synth",
    params: {
      attack: 0.08,
      decay: 0.36,
      sustain: 0.68,
      release: 0.5,
      cutoff: 1800,
      resonance: 0.8,
      gain: 0.42,
      lofiAmount: 0.1,
      detune: 12,
      drive: 0.1,
      vibratoRate: 3.8,
      vibratoDepth: 6,
      oscWaveformA: "triangle",
      oscWaveformB: "sine",
      oscMix: 0.55,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
    send: {
      delay: 0.18,
      reverb: 0.52,
      delayTone: 0.58,
      reverbTone: 0.54,
      reverbLowCut: 0.34,
      delayBus: "echoA",
      reverbBus: "hallB",
    },
  },
  {
    id: "synth-lofi-key",
    label: "Lo-fi Keys",
    type: "synth",
    params: {
      attack: 0.015,
      decay: 0.22,
      sustain: 0.42,
      release: 0.3,
      cutoff: 980,
      resonance: 1.8,
      gain: 0.44,
      lofiAmount: 0.45,
      detune: 5,
      drive: 0.34,
      vibratoRate: 4.6,
      vibratoDepth: 5,
      oscWaveformA: "square",
      oscWaveformB: "triangle",
      oscMix: 0.48,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-analog-bass",
    label: "Analog Bass",
    type: "synth",
    params: {
      attack: 0.005,
      decay: 0.2,
      sustain: 0.35,
      release: 0.16,
      cutoff: 1200,
      resonance: 1.6,
      gain: 0.62,
      lofiAmount: 0.03,
      detune: 4,
      drive: 0.28,
      vibratoRate: 1.8,
      vibratoDepth: 2.5,
      oscWaveformA: "square",
      oscWaveformB: "sawtooth",
      oscMix: 0.3,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-sub-bass",
    label: "Sub Bass",
    type: "synth",
    params: {
      attack: 0.008,
      decay: 0.14,
      sustain: 0.42,
      release: 0.2,
      cutoff: 800,
      resonance: 0.7,
      gain: 0.7,
      lofiAmount: 0,
      detune: 1.5,
      drive: 0.18,
      vibratoRate: 0.8,
      vibratoDepth: 1.2,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.2,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-supersaw",
    label: "Supersaw",
    type: "synth",
    params: {
      attack: 0.02,
      decay: 0.3,
      sustain: 0.58,
      release: 0.38,
      cutoff: 3600,
      resonance: 0.9,
      gain: 0.5,
      lofiAmount: 0,
      detune: 18,
      drive: 0.22,
      vibratoRate: 4.2,
      vibratoDepth: 7,
      oscWaveformA: "sawtooth",
      oscWaveformB: "sawtooth",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
    send: {
      delay: 0.24,
      reverb: 0.34,
      delayTone: 0.78,
      reverbTone: 0.66,
      reverbLowCut: 0.28,
      delayBus: "echoB",
      reverbBus: "hallB",
    },
  },
  {
    id: "synth-space-pluck",
    label: "Space Pluck",
    type: "synth",
    params: {
      attack: 0.001,
      decay: 0.14,
      sustain: 0.12,
      release: 0.16,
      cutoff: 4800,
      resonance: 2.7,
      gain: 0.46,
      lofiAmount: 0.02,
      detune: 9,
      drive: 0.14,
      vibratoRate: 4.8,
      vibratoDepth: 2.2,
      oscWaveformA: "triangle",
      oscWaveformB: "sawtooth",
      oscMix: 0.42,
      subOscMix: 0.04,
      noiseMix: 0.01,
      stereoWidth: 0.34,
      filterEnvAmount: 0.22,
    },
    send: {
      delay: 0.42,
      reverb: 0.24,
      delayTone: 0.82,
      reverbTone: 0.7,
      reverbLowCut: 0.36,
      delayBus: "echoB",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-dub-bass",
    label: "Dub Bass",
    type: "synth",
    params: {
      attack: 0.01,
      decay: 0.24,
      sustain: 0.48,
      release: 0.24,
      cutoff: 1100,
      resonance: 1.7,
      gain: 0.54,
      lofiAmount: 0.06,
      detune: 2.5,
      drive: 0.22,
      vibratoRate: 1.3,
      vibratoDepth: 1.2,
      oscWaveformA: "square",
      oscWaveformB: "triangle",
      oscMix: 0.28,
      subOscMix: 0.22,
      noiseMix: 0,
      stereoWidth: 0.12,
      filterEnvAmount: 0.12,
    },
    send: {
      delay: 0.3,
      reverb: 0.12,
      delayTone: 0.4,
      reverbTone: 0.38,
      reverbLowCut: 0.62,
      delayBus: "echoA",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-cinema-lead",
    label: "Cinema Lead",
    type: "synth",
    params: {
      attack: 0.012,
      decay: 0.2,
      sustain: 0.44,
      release: 0.3,
      cutoff: 3000,
      resonance: 1.1,
      gain: 0.46,
      lofiAmount: 0,
      detune: 11,
      drive: 0.18,
      vibratoRate: 4.1,
      vibratoDepth: 5.6,
      oscWaveformA: "sawtooth",
      oscWaveformB: "triangle",
      oscMix: 0.56,
      subOscMix: 0.04,
      noiseMix: 0.01,
      stereoWidth: 0.32,
      filterEnvAmount: 0.1,
    },
    send: {
      delay: 0.22,
      reverb: 0.46,
      delayTone: 0.74,
      reverbTone: 0.68,
      reverbLowCut: 0.32,
      delayBus: "echoB",
      reverbBus: "hallB",
    },
  },
  {
    id: "synth-pluck",
    label: "Pluck",
    type: "synth",
    params: {
      attack: 0,
      decay: 0.1,
      sustain: 0.08,
      release: 0.09,
      cutoff: 4200,
      resonance: 2.4,
      gain: 0.52,
      lofiAmount: 0.04,
      detune: 7,
      drive: 0.15,
      vibratoRate: 5.2,
      vibratoDepth: 3,
      oscWaveformA: "triangle",
      oscWaveformB: "square",
      oscMix: 0.55,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-bell",
    label: "Bell",
    type: "synth",
    params: {
      attack: 0.002,
      decay: 0.5,
      sustain: 0.12,
      release: 0.5,
      cutoff: 6500,
      resonance: 2.2,
      gain: 0.38,
      lofiAmount: 0,
      detune: 10,
      drive: 0.06,
      vibratoRate: 6.5,
      vibratoDepth: 9,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.65,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-acid-lead",
    label: "Acid Lead",
    type: "synth",
    params: {
      attack: 0.001,
      decay: 0.18,
      sustain: 0.34,
      release: 0.13,
      cutoff: 1700,
      resonance: 4.4,
      gain: 0.5,
      lofiAmount: 0.02,
      detune: 6,
      drive: 0.36,
      vibratoRate: 3.2,
      vibratoDepth: 4.5,
      oscWaveformA: "sawtooth",
      oscWaveformB: "square",
      oscMix: 0.45,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "synth-electric-piano",
    label: "Electric Piano",
    type: "synth",
    params: {
      attack: 0.004,
      decay: 0.32,
      sustain: 0.28,
      release: 0.28,
      cutoff: 3400,
      resonance: 1.6,
      gain: 0.44,
      lofiAmount: 0.06,
      detune: 4,
      drive: 0.08,
      vibratoRate: 4.9,
      vibratoDepth: 1.8,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.58,
      subOscMix: 0,
      noiseMix: 0.01,
      stereoWidth: 0.22,
      filterEnvAmount: 0.14,
    },
    send: {
      delay: 0.12,
      reverb: 0.22,
      delayTone: 0.66,
      reverbTone: 0.58,
      reverbLowCut: 0.3,
      delayBus: "echoA",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-tonewheel-organ",
    label: "Tonewheel Organ",
    type: "synth",
    params: {
      attack: 0.001,
      decay: 0.02,
      sustain: 0.92,
      release: 0.08,
      cutoff: 5200,
      resonance: 0.35,
      gain: 0.42,
      lofiAmount: 0,
      detune: 2,
      drive: 0.14,
      vibratoRate: 5.1,
      vibratoDepth: 3.2,
      oscWaveformA: "square",
      oscWaveformB: "triangle",
      oscMix: 0.34,
      subOscMix: 0.12,
      noiseMix: 0,
      stereoWidth: 0.16,
      filterEnvAmount: 0,
    },
    send: {
      delay: 0.08,
      reverb: 0.18,
      delayTone: 0.7,
      reverbTone: 0.62,
      reverbLowCut: 0.42,
      delayBus: "echoA",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-string-ensemble",
    label: "String Ensemble",
    type: "synth",
    params: {
      attack: 0.06,
      decay: 0.28,
      sustain: 0.74,
      release: 0.58,
      cutoff: 2400,
      resonance: 0.95,
      gain: 0.42,
      lofiAmount: 0.02,
      detune: 14,
      drive: 0.08,
      vibratoRate: 4.0,
      vibratoDepth: 4.2,
      oscWaveformA: "sawtooth",
      oscWaveformB: "triangle",
      oscMix: 0.62,
      subOscMix: 0,
      noiseMix: 0.005,
      stereoWidth: 0.34,
      filterEnvAmount: 0.08,
    },
    send: {
      delay: 0.1,
      reverb: 0.5,
      delayTone: 0.6,
      reverbTone: 0.64,
      reverbLowCut: 0.38,
      delayBus: "echoA",
      reverbBus: "hallB",
    },
  },
  {
    id: "synth-brass-section",
    label: "Brass Section",
    type: "synth",
    params: {
      attack: 0.018,
      decay: 0.16,
      sustain: 0.56,
      release: 0.2,
      cutoff: 2100,
      resonance: 1.25,
      gain: 0.46,
      lofiAmount: 0,
      detune: 7,
      drive: 0.18,
      vibratoRate: 4.2,
      vibratoDepth: 2.4,
      oscWaveformA: "sawtooth",
      oscWaveformB: "square",
      oscMix: 0.4,
      subOscMix: 0.05,
      noiseMix: 0.01,
      stereoWidth: 0.18,
      filterEnvAmount: 0.2,
    },
    send: {
      delay: 0.05,
      reverb: 0.22,
      delayTone: 0.56,
      reverbTone: 0.52,
      reverbLowCut: 0.44,
      delayBus: "custom",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-clarinet-ish",
    label: "Clarinet-ish",
    type: "synth",
    params: {
      attack: 0.012,
      decay: 0.14,
      sustain: 0.64,
      release: 0.22,
      cutoff: 1700,
      resonance: 1.9,
      gain: 0.4,
      lofiAmount: 0,
      detune: 1.5,
      drive: 0.05,
      vibratoRate: 5.6,
      vibratoDepth: 2.8,
      oscWaveformA: "square",
      oscWaveformB: "sine",
      oscMix: 0.26,
      subOscMix: 0,
      noiseMix: 0.004,
      stereoWidth: 0.08,
      filterEnvAmount: 0.06,
    },
    send: {
      delay: 0.04,
      reverb: 0.18,
      delayTone: 0.5,
      reverbTone: 0.48,
      reverbLowCut: 0.36,
      delayBus: "custom",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-flute-ish",
    label: "Flute-ish",
    type: "synth",
    params: {
      attack: 0.02,
      decay: 0.14,
      sustain: 0.72,
      release: 0.26,
      cutoff: 4200,
      resonance: 0.75,
      gain: 0.34,
      lofiAmount: 0,
      detune: 2.2,
      drive: 0.03,
      vibratoRate: 5.3,
      vibratoDepth: 5.4,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.2,
      subOscMix: 0,
      noiseMix: 0.02,
      stereoWidth: 0.12,
      filterEnvAmount: 0.04,
    },
    send: {
      delay: 0.08,
      reverb: 0.3,
      delayTone: 0.72,
      reverbTone: 0.74,
      reverbLowCut: 0.34,
      delayBus: "echoA",
      reverbBus: "hallB",
    },
  },
  {
    id: "synth-nylon-guitar-ish",
    label: "Nylon Guitar-ish",
    type: "synth",
    params: {
      attack: 0.001,
      decay: 0.2,
      sustain: 0.16,
      release: 0.18,
      cutoff: 3000,
      resonance: 2.1,
      gain: 0.42,
      lofiAmount: 0.03,
      detune: 3.2,
      drive: 0.06,
      vibratoRate: 4.4,
      vibratoDepth: 1.2,
      oscWaveformA: "triangle",
      oscWaveformB: "square",
      oscMix: 0.48,
      subOscMix: 0.02,
      noiseMix: 0.01,
      stereoWidth: 0.18,
      filterEnvAmount: 0.24,
    },
    send: {
      delay: 0.16,
      reverb: 0.2,
      delayTone: 0.68,
      reverbTone: 0.58,
      reverbLowCut: 0.4,
      delayBus: "echoA",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-marimba-ish",
    label: "Marimba-ish",
    type: "synth",
    params: {
      attack: 0.001,
      decay: 0.24,
      sustain: 0.06,
      release: 0.11,
      cutoff: 5200,
      resonance: 2.6,
      gain: 0.4,
      lofiAmount: 0,
      detune: 1.2,
      drive: 0.04,
      vibratoRate: 3.8,
      vibratoDepth: 0.6,
      oscWaveformA: "sine",
      oscWaveformB: "triangle",
      oscMix: 0.7,
      subOscMix: 0,
      noiseMix: 0.004,
      stereoWidth: 0.14,
      filterEnvAmount: 0.18,
    },
    send: {
      delay: 0.06,
      reverb: 0.26,
      delayTone: 0.74,
      reverbTone: 0.62,
      reverbLowCut: 0.34,
      delayBus: "custom",
      reverbBus: "roomA",
    },
  },
  {
    id: "synth-choir-pad",
    label: "Choir Pad",
    type: "synth",
    params: {
      attack: 0.09,
      decay: 0.24,
      sustain: 0.76,
      release: 0.62,
      cutoff: 2100,
      resonance: 1.05,
      gain: 0.38,
      lofiAmount: 0.01,
      detune: 10,
      drive: 0.05,
      vibratoRate: 4.6,
      vibratoDepth: 3.5,
      oscWaveformA: "triangle",
      oscWaveformB: "square",
      oscMix: 0.36,
      subOscMix: 0,
      noiseMix: 0.012,
      stereoWidth: 0.28,
      filterEnvAmount: 0.02,
    },
    send: {
      delay: 0.06,
      reverb: 0.56,
      delayTone: 0.52,
      reverbTone: 0.58,
      reverbLowCut: 0.48,
      delayBus: "echoA",
      reverbBus: "hallB",
    },
  },
  {
    id: "drums-tight-kit",
    label: "Tight Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.09,
      sustain: 0,
      release: 0.04,
      cutoff: 8600,
      resonance: 0.2,
      gain: 0.72,
      lofiAmount: 0,
      detune: 0,
      drive: 0.06,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-heavy-kit",
    label: "Heavy Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.18,
      sustain: 0,
      release: 0.08,
      cutoff: 7000,
      resonance: 0.4,
      gain: 0.92,
      lofiAmount: 0.08,
      detune: 0,
      drive: 0.18,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-dusty-kit",
    label: "Dusty Kit",
    type: "drums",
    params: {
      attack: 0.002,
      decay: 0.14,
      sustain: 0,
      release: 0.07,
      cutoff: 5200,
      resonance: 0.5,
      gain: 0.7,
      lofiAmount: 0.35,
      detune: 0,
      drive: 0.22,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-house-kit",
    label: "House Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.13,
      sustain: 0,
      release: 0.05,
      cutoff: 9000,
      resonance: 0.15,
      gain: 0.78,
      lofiAmount: 0.02,
      detune: 0,
      drive: 0.12,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-boom-bap",
    label: "Boom Bap",
    type: "drums",
    params: {
      attack: 0.002,
      decay: 0.2,
      sustain: 0,
      release: 0.09,
      cutoff: 4300,
      resonance: 0.75,
      gain: 0.82,
      lofiAmount: 0.42,
      detune: 0,
      drive: 0.34,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
  {
    id: "drums-airy-kit",
    label: "Airy Kit",
    type: "drums",
    params: {
      attack: 0.001,
      decay: 0.1,
      sustain: 0,
      release: 0.04,
      cutoff: 9800,
      resonance: 0.2,
      gain: 0.66,
      lofiAmount: 0,
      detune: 0,
      drive: 0.06,
      vibratoRate: 0,
      vibratoDepth: 0,
      oscWaveformA: "triangle",
      oscWaveformB: "triangle",
      oscMix: 0.5,
      subOscMix: 0,
      noiseMix: 0,
      stereoWidth: 0.25,
      filterEnvAmount: 0,
    },
  },
];

export const getPresetsForType = (type: Track["type"]): InstrumentPreset[] =>
  INSTRUMENT_PRESETS.filter((preset) => preset.type === type);

export const getMatchingPresetId = (type: Track["type"], params: InstrumentParams, send?: Track["send"]): string | null => {
  const match = getPresetsForType(type).find((preset) =>
    preset.params.oscWaveformA === params.oscWaveformA &&
    preset.params.oscWaveformB === params.oscWaveformB &&
    numericInstrumentFields.every((field) => nearlyEqual(preset.params[field], params[field])) &&
    (!send ||
      (() => {
        const presetSend = { ...DEFAULT_PRESET_SEND, ...preset.send };
        return (
          nearlyEqual(presetSend.delay, send.delay) &&
          nearlyEqual(presetSend.reverb, send.reverb) &&
          nearlyEqual(presetSend.delayTone, send.delayTone) &&
          nearlyEqual(presetSend.reverbTone, send.reverbTone) &&
          nearlyEqual(presetSend.reverbLowCut, send.reverbLowCut) &&
          presetSend.delayBus === send.delayBus &&
          presetSend.reverbBus === send.reverbBus
        );
      })())
  );
  return match?.id ?? null;
};


